#' Create Pie Chart from Table
#'
#' \code{create_pie} takes output from one of the \code{covidCluster::*_table}
#' functions and produces a pie chart.
#'
#' @param .table The output of \code{\link{create_table}}, which is a one-way
#'   \code{\link[janitor]{tabyl}} encoded to assist visualization
#'
#' @param .by The variable to chart; defaults to the first column of
#'   \code{.table}
#'
#' @param incl_missing Should the chart include missing values as a category?
#'
#' @param title The title of the chart; defaults to a title-case version of the
#'   variable name
#'
#' @param legend_title The title of the chart legend; defaults to the chart
#'   title
#'
#' @param palette The color palette to use; this is a material design color
#'   palette generated by \code{\link[ggsci]{pal_material}}; see that
#'   function for details and available choices
#'
#' @param bottom_legend Should the legend be positioned at the bottom or on the
#'   right side?
#'
#' @param background What should the background color be? Defaults to a light gray.
#'
#' @param dodge Change the position of the labels along the radius of the
#'   circle; useful for separating overlapping labels. A value of \code{0}
#'   leaves the labels at the mid-point of the pie chart radius; a value of
#'   \code{1} spaces them evenly across the radius. Values in-between \code{0}
#'   and \code{1} spread the labels out across that fraction of the radius
#'   (centered on the midpoint).
#'
#' @return A ggplot object
#'
#' @export
plot_pie <- function(
  .table,
  .by = NULL,
  incl_missing = FALSE,
  title = NULL,
  legend_title = title,
  palette = "blue",
  bottom_legend = TRUE,
  background = "gray93",
  dodge = 0
) {

  # Make sure `.by` is a symbol; defaults to the summarized variable
  if (rlang::is_empty(.by)) {
    .by <- .table %>%
      colnames() %>%
      extract2(1) %>%
      rlang::sym()
  } else {
    .by <- rlang::ensym(.by)
  }

  # Remove missing data, if desired
  if (rlang::is_false(incl_missing)) {
    .table %>%
      dplyr::filter(!!.by != "Missing") ->
      .table
  }

  # Create color palette
  pal <- ggsci::pal_material(
    palette = palette,
    n = NROW(.table) + 1,
    reverse = TRUE
  )

  # Set title to title-case `.by` if NULL
  if (rlang::is_empty(title)) {
    title <- rlang::as_name(.by) %>% janitor::make_clean_names(case = "title")
  }

  # Calculate percentages
  .table %>%
    dplyr::mutate(
      pct = .data[["n"]] / sum(.data[["n"]], na.rm = TRUE)
    ) ->
    .table

  # Create plot
  plt <- ggplot2::ggplot(
    .table,
    ggplot2::aes(x = 1, y = .data[["pct"]], fill = !!.by)
  ) +
    ggplot2::geom_col(width = 1, position = "fill") +
    ggtext::geom_richtext(
      ggplot2::aes(
        y = cumsum(rev(.data[["pct"]])) - 0.5*rev(.data[["pct"]]),
        label = paste0(
          "**", rev(.data[["n"]]), "** ",
          "(", round(100*rev(.data[["pct"]])), "%)"
        ),
        color = rev(!!.by),
      ),
      size = 5,
      fill = background,
      position = ggplot2::position_dodge2(width = dodge),
      show.legend = FALSE
    ) +
    ggplot2::coord_polar("y", start = 0, direction = -1) +
    ggplot2::scale_color_manual(
      name = legend_title,
      values = pal(NROW(.table)),
      aesthetics = c("color", "fill")
    ) +
    ggplot2::ggtitle(title) +
    ggthemes::theme_fivethirtyeight() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(
        size = 28,
        face = "bold",
        hjust = 0.5,
        color = "gray30"
      ),
      legend.title = ggplot2::element_text(
        size = 18,
        face = "bold",
        color = "grey30"
      ),
      legend.text = ggplot2::element_text(
        size = 14,
        color = "gray30"
      ),
      legend.background = ggplot2::element_rect(color = NA, fill = background),
      legend.box.background = ggplot2::element_rect(color = NA, fill = background),
      legend.key = ggplot2::element_rect(color = NA, fill = background),
      panel.background = ggplot2::element_rect(color = NA, fill = background),
      panel.border = ggplot2::element_blank(),
      panel.grid.major = ggplot2::element_blank(),
      plot.background = ggplot2::element_rect(color = NA, fill = background),
      line = ggplot2::element_blank(),
      axis.text = ggplot2::element_blank()
    )

  if (rlang::is_false(bottom_legend)) {
    plt <- plt + ggplot2::theme(
      legend.position = "right",
      legend.direction = "vertical"
    )
  }

  attr(plt, which = "background") <- background

  plt
}

#' Create Bar Chart from Table
#'
#' \code{create_bar} takes output from one of the \code{*_table} functions and
#' produces a bar chart.
#'
#' @param .table The output of \code{\link{create_table}} which is a one-way
#'   \code{\link[janitor]{tabyl}} encoded to assist visualization
#'
#' @param .by The variable to chart; defaults to the first column of
#'   \code{.table}, which will always be correct if the output is from a
#'   \code{*_table} function
#'
#' @param incl_missing Should the chart include missing values as a category?
#'
#' @param title The title of the chart; defaults to a title-case version of the
#'   variable name
#'
#' @param x_lab Label for the x-axis; defaults to no label
#'
#' @param y_lab Label for the y-axis; defaults to no label
#'
#' @param legend Should a legend be displayed? Bar charts should usually not
#'   require a legend, so the default is \code{FALSE}
#'
#' @param legend_title The title of the chart legend; defaults to the chart
#'   title
#'
#' @param bottom_legend Should the legend be positioned at the bottom or on the
#'   right side? Default is bottom.
#'
#' @param palette The color palette to use; this is a material design color
#'   palette generated by \code{\link[ggsci]{pal_material}}; see that
#'   function for details and available choices
#'
#' @param background What should the background color be? Defaults to a light
#'   gray to lessen eye strain.
#'
#' @return A ggplot object
#'
#' @export
plot_bar <- function(
  .table,
  .by = NULL,
  incl_missing = FALSE,
  title = NULL,
  x_lab = NULL,
  y_lab = NULL,
  legend = FALSE,
  legend_title = title,
  bottom_legend = TRUE,
  palette = "blue",
  background = "gray93"
) {

  # Make sure `.by` is a symbol; defaults to the summarized variable
  if (rlang::is_empty(.by)) {
    .by <- .table %>%
      colnames() %>%
      extract2(1) %>%
      rlang::sym()
  } else {
    .by <- rlang::ensym(.by)
  }

  # Remove missing data, if desired
  if (rlang::is_false(incl_missing)) {
    .table %>%
      dplyr::filter(!!.by != "Missing") ->
      .table
  }

  # Create color palette
  pal <- ggsci::pal_material(
    palette = palette,
    n = NROW(.table) + 1,
    reverse = TRUE
  )

  # Set title to title-case `.by` if NULL
  if (rlang::is_empty(title)) {
    title <- rlang::as_name(.by) %>% janitor::make_clean_names(case = "title")
  }

  # Calculate percentages
  .table %>%
    dplyr::mutate(pct = .data[["n"]] / sum(.data[["n"]], na.rm = TRUE)) ->
    .table

  # Create plot
  plt <- ggplot2::ggplot(
    .table,
    ggplot2::aes(x = !!.by, y = .data[["n"]], fill = !!.by)
  ) +
    ggplot2::geom_col(show.legend = legend) +
    ggtext::geom_textbox(
      ggplot2::aes(
        y = .data[["n"]],
        label = paste0(
          "**", .data[["n"]], "** ",
          "(", round(100*.data[["pct"]]), "%)"
        ),
      ),
      width = 0.9/15,
      vjust = 0,
      halign = 0.5,
      size = 14 * 0.35278,
      color = "gray30",
      fill = background,
      show.legend = FALSE
    ) +
    ggplot2::scale_color_manual(
      name = legend_title,
      values = pal(NROW(.table)),
      aesthetics = c("color", "fill")
    ) +
    ggplot2::coord_cartesian(ylim = c(0, 1.1*max(.table[["n"]]))) +
    ggplot2::ggtitle(title) +
    ggplot2::xlab(x_lab) +
    ggplot2::ylab(y_lab) +
    ggthemes::theme_fivethirtyeight(base_size = 14) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(
        size = 28,
        face = "bold",
        hjust = 0.5,
        color = "gray30"
      ),
      legend.title = ggplot2::element_text(
        size = 18,
        face = "bold",
        color = "grey30"
      ),
      legend.text = ggplot2::element_text(
        size = 14,
        color = "gray30"
      ),
      legend.background = ggplot2::element_rect(color = NA, fill = background),
      legend.box.background = ggplot2::element_rect(color = NA, fill = background),
      legend.key = ggplot2::element_rect(color = NA, fill = background),
      panel.background = ggplot2::element_rect(color = NA, fill = background),
      panel.border = ggplot2::element_blank(),
      panel.grid.major.x = ggplot2::element_blank(),
      plot.background = ggplot2::element_rect(color = NA, fill = background),
      line = ggplot2::element_blank(),
      axis.text = ggplot2::element_text(size = 16),
      axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1),
      axis.title.x = purrr::when(
        rlang::is_empty(x_lab) ~ ggplot2::element_blank(),
        ~ ggplot2::element_text(size = 18)
      ),
      axis.title.y = purrr::when(
        rlang::is_empty(y_lab) ~ ggplot2::element_blank(),
        ~ ggplot2::element_text(size = 18)
      ),
    )

  if (rlang::is_false(bottom_legend)) {
    plt <- plt + ggplot2::theme(
      legend.position = "right",
      legend.direction = "vertical"
    )
  }

  attr(plt, which = "background") <- background

  plt
}
